# Generated by Django 2.2.11 on 2021-01-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourproperty', '0002_auto_20210113_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateproperty',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_user_type', to='ourproperty.UserType'),
        ),
    ]
