# Generated by Django 2.2.11 on 2021-01-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourproperty', '0003_auto_20210113_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estateproperty',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='estateproperty',
            name='user_type',
        ),
        migrations.AddField(
            model_name='estateproperty',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_dealer', to='ourproperty.UserType'),
        ),
    ]
