# Generated by Django 2.2.11 on 2021-01-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproperty', '0003_auto_20210113_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateproperty',
            name='dealer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
